/**
 * LMS Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentResponseDto } from './studentResponseDto';


export interface AuthTokenResponseDto { 
    /**
     * JWT Authentication Bearer token
     */
    token: string;
    /**
     * Authenticated student info
     */
    user: StudentResponseDto;
}

