/**
 * LMS Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticateStudentDto { 
    /**
     * Registered student email
     */
    email: string;
    /**
     * Account password
     */
    password: string;
}

