/**
 * LMS Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuickAddStudentDto { 
    /**
     * Full name of the student
     */
    name?: string;
    /**
     * Email address of the student
     */
    email?: string;
    /**
     * Contact phone number
     */
    phone?: string;
}

