/**
 * LMS Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentResponseDto { 
    /**
     * Unique student identifier
     */
    id: string;
    /**
     * Student full name
     */
    name: string;
    /**
     * Student email
     */
    email: string;
    /**
     * Student roll number
     */
    rollNo?: string;
}

